global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'minio'
    static_configs:
      - targets: ['minio:9000']
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']