spring:
    application:
        name: auth
    h2:
        console:
            enabled: true
            path: /h2-console
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
    instance:
        preferIpAddress: true
