spring:
    application:
        name: auth
    datasource:
        url: jdbc:postgresql://localhost:5432/chat
        username: myuser
        password: 0000
        driver-class-name: org.postgresql.Driver
    jpa:
        properties:
            hibernate:
                show_sql: true
                format_sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
    instance:
        preferIpAddress: true
